name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: tests-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    env:
      CARGO_INCREMENTAL: "0"
      NEXTEST_SHOW_PROGRESS: "none"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7
        with:
          toolchain: 1.94.0

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        continue-on-error: true
        with:
          shared-key: ${{ runner.os }}-tests-${{ hashFiles('rust-toolchain.toml') }}
      - name: Cache cargo bin
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        continue-on-error: true
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-cargo-bin
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-cargo-bin
      - name: Install nextest
        uses: taiki-e/install-action@aba36d755ec7ca22d38b12111787c26115943952 # v2
        with:
          tool: cargo-nextest@0.9.129

      - name: Run checks
        run: scripts/check.sh --no-audit
